apiVersion: v1
kind: Pod
metadata:
  name: online-inference-probes
  labels:
    app: online-inference
spec:
  containers:
    - image: juliakorp/online_model:v2
      command: [ "uvicorn", "online_model:app", "--host", "0.0.0.0", "--port", "8080" ]
      name: online-inference-resources
      resources:
        requests:
          memory: "100Mi"
          cpu: "250m"
        limits:
          memory: "1G"
          cpu: "1"
      ports:
        - containerPort: 8080
      livenessProbe:
        httpGet:
          path: /health
          port: 8080
        initialDelaySeconds: 30
        periodSeconds: 5
      readinessProbe:
        httpGet:
          path: /health
          port: 8080
        initialDelaySeconds: 10
        periodSeconds: 10