apiVersion: apps/v1
kind: Deployment
metadata:
  name: online-inference-deployment-blue-green
  labels:
    app: online-inference
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 0
  selector:
    matchLabels:

      app: online-inference
  template:
    metadata:
      labels:
        app: online-inference
    spec:
      containers:
        - name: online-inference-deployment
          image: juliakorp/online_model:v1
          ports:
            -  containerPort: 8080